In [1]:
import numpy as np
import matplotlib as mp

1 Sea la matriz cuadrada

a) Cree un notebook de Python y almacene la matriz A. Todas las operaciones solicitadas hágalas sobre la matiz original.

In [2]:
A=np.matrix(([1,1,0],[0,2,3],[3,3,1]))
A

matrix([[1, 1, 0],
        [0, 2, 3],
        [3, 3, 1]])

b) Sume a la tercera fila, la primera fila multiplicada por -3.

In [4]:
A[2,:]=A[2,:]+3*A[0,:]
A

matrix([[1, 1, 0],
        [0, 2, 3],
        [9, 9, 1]])

c) Intercambie la primera columna con la tercera.

In [5]:
A[:,[2,0]]=A[:,[0,2]]
A

matrix([[0, 1, 1],
        [3, 2, 0],
        [1, 9, 9]])

d) Construya una nueva matriz cuyas columnas sean las columnas primera y tercera de A.

In [14]:
B= np.concatenate([A[:,0], A[:,2]], axis=1)
B

matrix([[0, 1],
        [3, 0],
        [1, 9]])

e) Construya una nueva matriz cuyas filas sean las columnas primera y tercera de A.


In [16]:
BT=np.transpose(B)
BT

matrix([[0, 3, 1],
        [1, 0, 9]])

f) Construya la matriz añadiendo la matriz identidad de rango 3 a la derecha de la matriz A.

In [17]:
A=np.matrix(([1,1,0],[0,2,3],[3,3,1]))
I=np.eye(3)
AI=np.concatenate((A,I),axis=1)
AI

matrix([[1., 1., 0., 1., 0., 0.],
        [0., 2., 3., 0., 1., 0.],
        [3., 3., 1., 0., 0., 1.]])

g) Aplique el comando np.lialg.solve (lea la ayuda de Numpy) a las matrices A e I, indique qué se obtiene
como resultado.

In [18]:
Ainv=np.linalg.solve(A,I)
Ainv

array([[-3.5, -0.5,  1.5],
       [ 4.5,  0.5, -1.5],
       [-3. , -0. ,  1. ]])

h) Ejecute el producto matricial (lea la ayuda de Numpy) de la matriz A con la matriz obtenida en el literal
anterior. ¿Qué puede decir de la matriz AI?


In [19]:
np.matmul(A,Ainv)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

2 Resuelve con Pythonlos siguientes sitemas de ecuaciones, utilice la idea del ejercicio anterior:


In [21]:
A1=np.matrix(([2,-1,3],[4,2,1],[3,2,-5]))
B1=np.matrix(([1],[2],[-4]))
x=np.linalg.solve(A1,B1)
x

matrix([[-0.43902439],
        [ 1.34146341],
        [ 1.07317073]])

El sistema de ecuaciones tiene solo una solución

In [22]:
A2=np.matrix(([-1,3],[2,0],[-1,1]))
B2=np.matrix(([-2],[3],[1]))
x2=np.linalg.solve(A2,B2)
x2

LinAlgError: Last 2 dimensions of the array must be square

El sistema de ecuaciones no tiene solución

3 Lea la ayuda de Numpy y para la matriz cuadrada :

In [34]:
A=np.matrix(([1,4,0],[0,2,3],[3,3,-7]))
A

matrix([[ 1,  4,  0],
        [ 0,  2,  3],
        [ 3,  3, -7]])

a) Halle el valor mínimo dentro de cada fila de A (min).

In [35]:
A.min(1)

matrix([[ 0],
        [ 0],
        [-7]])

b) Ordene los elementos de A en orden descendente dentro de cada columna (sort).

In [36]:
A=-A
A.sort(axis=0)
A=-A
A

matrix([[ 3,  4,  3],
        [ 1,  3,  0],
        [ 0,  2, -7]])

c) Ordene los elementos de A en orden ascendente dentro de cada fila .

In [38]:
A.sort(axis=1)
A

matrix([[ 3,  3,  4],
        [ 0,  1,  3],
        [-7,  0,  2]])

d) Forme una lista con los elementos de A ordenada de forma ascendente.

In [41]:
B=np.reshape(A,9)
B.sort(axis=1)
B

matrix([[-7,  0,  0,  1,  2,  3,  3,  3,  4]])

e) Hallar el máximo en valor absoluto de los elementos de A.

In [42]:
BA=np.absolute(B)
np.max(BA)

7

4 En una sola orden de Python genere una matriz 3 × 5 cuyo único elemento es 7, utilice np.ones

In [44]:
A=7*np.ones((3,5))
A

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

5 Con una sola orden de Python genere una matriz aleatoria 4 × 4 de números reales entre -5 y 5. Utilice
np.linspace y np.reshape

In [46]:
np.reshape(np.linspace(-5,5,num=16),(4,4))

array([[-5.        , -4.33333333, -3.66666667, -3.        ],
       [-2.33333333, -1.66666667, -1.        , -0.33333333],
       [ 0.33333333,  1.        ,  1.66666667,  2.33333333],
       [ 3.        ,  3.66666667,  4.33333333,  5.        ]])

6 Con una sola orden de Python genere una matriz aleatoria 4 × 4 de números enteros entre -5 y 5. Investiga
como hacerlo.

array([[0.92416955, 0.55894623, 0.76319871, 0.57251296, 0.50142565],
       [0.71574282, 0.96904857, 0.45908156, 0.54522561, 0.87756438],
       [0.82491657, 0.04385817, 0.48889099, 0.34335315, 0.07461917],
       [0.91251819, 0.02457392, 0.24945557, 0.69589859, 0.95767925],
       [0.99329646, 0.19628585, 0.22575781, 0.40089169, 0.5800073 ]])

In [45]:
np.random.randint(-5,5,size=(4,4))

array([[ 3,  2,  4, -4],
       [-4,  2, -5,  1],
       [ 3,  3,  3, -3],
       [ 0, -4,  2, -3]])

7 Considere la siguiente orden de Python (debe importar numpy com np):

In [71]:
A=np.random.rand(16)
A=A.reshape((4,4))
A

array([[0.36413253, 0.47155107, 0.29137119, 0.64823522],
       [0.05058991, 0.07423439, 0.45964084, 0.39049918],
       [0.72145842, 0.13842607, 0.25269019, 0.43944817],
       [0.88511928, 0.46456704, 0.21291965, 0.39557646]])

a) Defina una matriz B formada por las filas pares de la matriz A.

In [72]:
B= np.concatenate([A[1::2]], axis=1)
B

array([[0.05058991, 0.07423439, 0.45964084, 0.39049918],
       [0.88511928, 0.46456704, 0.21291965, 0.39557646]])

b) Defina una matriz C formada porlas columnas impares de la matriz A.

In [73]:
C= np.concatenate([A[:,::2]], axis=1)
C

array([[0.36413253, 0.29137119],
       [0.05058991, 0.45964084],
       [0.72145842, 0.25269019],
       [0.88511928, 0.21291965]])

c) Defina una matriz d formada por la tercera columna de A.

In [74]:
D= np.concatenate([A[:,3]], axis=0)
D

array([0.64823522, 0.39049918, 0.43944817, 0.39557646])

d) Elimina la tecera fila de la matriz A.

In [91]:
np.delete(A,2,0)

array([[0.36413253, 0.47155107, 0.29137119, 0.64823522],
       [0.05058991, 0.07423439, 0.45964084, 0.39049918],
       [0.88511928, 0.46456704, 0.21291965, 0.39557646]])

8  Genere una lista de valores en una variable x des de 0 hasta 2π en pasos de π/4. Con una sola orden de Python
crea una matriz cuya primera fila es x, su sefunda fila es el seno de cada elemento de xy cuya tercera fila el
coseno de cada elmento de x.

In [96]:
x=np.arange (0, 2*np.pi , np.pi/4)
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

In [101]:
X = np.resize(np.concatenate([x, np.sin(x),np.cos(x)], axis=0),(3,8))
X

array([[ 0.00000000e+00,  7.85398163e-01,  1.57079633e+00,
         2.35619449e+00,  3.14159265e+00,  3.92699082e+00,
         4.71238898e+00,  5.49778714e+00],
       [ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,
         7.07106781e-01,  1.22464680e-16, -7.07106781e-01,
        -1.00000000e+00, -7.07106781e-01],
       [ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17,
        -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
        -1.83697020e-16,  7.07106781e-01]])

9 Defina un vector a formado por los cuatro primeros números impares y otro b por los cuatro pirmeros números
pares. de qué manera se debe operar entre los vectores a y b para construir la matriz:


In [110]:
a=np.transpose(np.matrix([[1,3,5,7]]))
b=np.matrix([[2,4,6,8]])
c=np.matmul(a,b)
c

matrix([[ 2,  4,  6,  8],
        [ 6, 12, 18, 24],
        [10, 20, 30, 40],
        [14, 28, 42, 56]])

10 Construye una matriz n × n, C = (cij )

En este caso la matriz voy a hacerla de n=6, se puede hacer una funcion con argumento n pero aja.

In [114]:
C=np.zeros((6,6))
for i in range(0,6):
    for j in range(0,6):
        if i==j:
            C[i,j]=i*j
        else:
            C[i,j]=np.cos(i*j)
C

array([[ 0.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 1.        ,  1.        , -0.41614684, -0.9899925 , -0.65364362,
         0.28366219],
       [ 1.        , -0.41614684,  4.        ,  0.96017029, -0.14550003,
        -0.83907153],
       [ 1.        , -0.9899925 ,  0.96017029,  9.        ,  0.84385396,
        -0.75968791],
       [ 1.        , -0.65364362, -0.14550003,  0.84385396, 16.        ,
         0.40808206],
       [ 1.        ,  0.28366219, -0.83907153, -0.75968791,  0.40808206,
        25.        ]])

11 Construye de tres maneras distinta la matriz:

In [119]:
C=np.zeros((4,4))
for i in range(0,4):
    for j in range(0,4):
        C[i,j]=i+1
C

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [118]:
uno=np.ones((4,4))
for i in range(0,4):
    uno[i,:]=uno[i,:]*i+1
uno


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [128]:
tres=np.ones((4,4))

for n in range(1,5):
    for i in range(0,4):
        for j in range(0,4):
            tres[i,j]=n
tres


array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

12  Genere una matriz cuadrada de orden 5 cualquiera. con una sola orden cambie los lementos de su diagonal a
0.

In [131]:
m=np.ones((5,5))
for i in range(0,5):
    for j in range(0,5):
        if i==j:
            m[i,j]=0
m

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

16 Genera una matriz aleatoria de orden 5 × 5 con valores entre −4 y 4. Con una sola instrucción poner en 0
todos los valores de la matriz que se encuentren entre -1 y 1.


In [169]:
ma=np.random.randint(-4,4,size=(5,5))
for i in range(0,5):
    for j in range(0,5):
        if ma[i,j] in range(-1,2):
            ma[i,j]=0
ma

array([[-4, -2,  0, -2,  2],
       [-3,  3, -3,  2,  0],
       [ 0,  3,  0,  3,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  2, -2, -2, -3]])

17 De tres formas distintas (cada una en una sola instrucción), averiguar el número de elementos de una matriz.

In [154]:
m=np.random.randint(100, size=(5,9))

In [155]:
m.shape

(5, 9)

In [158]:
np.shape(m)

(5, 9)

In [157]:
filas=len(m)
columnas=len(m[0])
(filas,columnas)

(5, 9)

18  Suma un escalar a todos los elementos de una matriz. Genera la matriz de manera aleatoria con cuatro filas
y seis columnas.

In [152]:
e=5
m= np.random.randint(100, size=(4,6))
print(m)
for i in range(0,4):
    for j in range(0,6):
        m[i,j]= m[i,j]+e
print(m)

[[ 5 29 93  0  8 13]
 [69 26 76 28 13 15]
 [26 61 52 93 86 34]
 [ 7 48 21 77 68 50]]
[[10 34 98  5 13 18]
 [74 31 81 33 18 20]
 [31 66 57 98 91 39]
 [12 53 26 82 73 55]]


19  Genera las siguientes vectores:

a) Un vector de 1 hasta 101 en pasos de 1.

In [134]:
m=np.arange (1, 102 , 1)
m

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

b) Un vector de 6 a 3 decreciendo en 0.5 unidades.

In [140]:
v=np.arange(6,2.5,-0.5)
v

array([6. , 5.5, 5. , 4.5, 4. , 3.5, 3. ])

c) Un vector de 5.3 a 9.2 en pasos de 0.7

In [144]:
vc=np.arange(5.3,9.3,0.7)
vc

array([5.3, 6. , 6.7, 7.4, 8.1, 8.8])

d) Una sucesión de 45 elementes que sean enteros desde de 1 hasta 10 en forma aleatoria.

In [146]:
vd=np.random.randint(1,10,45)
vd

array([6, 1, 5, 5, 6, 5, 1, 7, 4, 1, 1, 4, 2, 1, 5, 9, 5, 9, 8, 3, 3, 1,
       7, 7, 9, 6, 5, 4, 6, 8, 4, 1, 4, 5, 9, 7, 2, 1, 5, 9, 3, 1, 4, 9,
       7])